### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [zacjones93/firehose-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by zacjones93** [comment]
Ah, thanks for the catch @Mikeysax! Looks like adding `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">` fixes the issue! 

![screen recording 2017-10-24 at 04 49 pm](https://user-images.githubusercontent.com/6188161/31973536-6dd0b0c0-b8db-11e7-93b3-be1690280382.gif)

![](https://media.giphy.com/media/13XW2MJE0XCoM0/giphy.gif)

**Comment by Mikeysax** [comment]
:+1:
